### ISSUE TITLE
How to capture the event upon a module's load or present.

### ISSUE THREAD

**Issue by model-collapse** [vugu/vugu#119]
**Question**
I want to start a go routine right after one module's creation / present. Is there any event in Vugu like onload in JS? I don't think it is a good idea to start that routine in the event handler of the parent module after the change of the vg-if value ?

**Is your question related to a problem? Please describe.**

**Suggested Changes**
If applicable, please provide any suggestions of how to improve.

**Additional context**
Add any other context, info, files, etc. related to your question.

**Comment by bradleypeabody** [comment]
You can use `BeforeBuild()` (see https://www.vugu.org/doc/components) as a way to get a callback when the component is rendered.  Note that it will be called each time, so if you want something to happen only the first time you'll need to that state in a variable on your component.

However you'll also need an EventEnv if you want make updates from the goroutine, in order to lock properly.  EventEnv is documented under DOMEvents here https://www.vugu.org/doc/dom-events.  Unfortunately to get an instance you'll have to use the not-yet-documented `vuguSetup` mechanism to get a copy of EventEnv at startup and then make it available to your components.  See here https://github.com/vugu/vugu/blob/master/wasm-test-suite/test-011-wire/setup.go for an example of creating a vuguSetup function that has access to EventEnv and gives a function which can be used to inject it into an component.

It's easier to do than it sounds ☺️. I'll make it a point to put together a good example of all this working soon.  But for now if you do the above it should work.

**Comment by model-collapse** [comment]
Thanks very much, vugu will definitely be a great framework!

**Comment by bradleypeabody** [comment]
I'm going to go ahead and close this now.  Feel free to make another issue if more questions or ask on Slack.
