### ISSUE TITLE
Allow the creation of namespaced elements

### ISSUE THREAD

**Issue by tbe** [vugu/vugu#123]
**Is your feature request related to a problem? Please describe.**
Some commonly used objects, like `svg` must be created within a namespace. Currently this is not supported in `vugu`. It requires the usage of `createElementNS` in JS.

**Describe the solution you'd like**
After a rough look over the code, the following is missing
- create a new `opcodeSetElementNS`
- implement the js code to call `createElementNS`
- check if a node contains a namespace and set the correct opcode

`VGNode` already has a namespace attribute, but as far as i have seen it is not used right now. 

**Describe alternatives you've considered**
One could always use `syscall/js` but this, if at all, a bad workaround.

**Comment by bradleypeabody** [comment]
There is a note in the parser code to add a check for upper case to distinguish `<pkg:Comp>` from `<ns:tag>`.  Checking for the capital letter would be an easy way to distinguish namespaced tags from component references.

Then, I wonder if we really need a new opcode or if the attribute is called "svg:line" then we could check for the colon in the opcodeSetElement code and call createElementNS there as needed.  I'm actually not clear myself on what conditions cause the [Go HTML parser](https://godoc.org/golang.org/x/net/html) (which we use a fork of for Vugu) to populate the `Namespace` field instead of `Key` on a Node.  I think with a clear understanding of that we could see what the best way is of piping that information into the UI is.

**Comment by tbe** [comment]
Just seen, it is not that easy at all. `createElementNS` requires the namespace as URL. So, for `svg` that would be `http://www.w3.org/2000/svg`.

For `svg` and `math` ( supported by the HTML parser out of the box ), the namespace URL's could be provided by vugu from an internal map.

Leaves two questions:
- How does a user provide other namespace URLs?
- Should the mapping short NS -> URL be done in JS or Go?

**Comment by bradleypeabody** [comment]
Makes sense.  If you can fiddle with the Go HTML parser and see how it handles different situations, this would help.  Like I don't think I've ever seen the `Namespace` field not-empty in any HTML I've ever parsed with that thing.  I'm not sure if it's supposed to be the full namespace like `http://www.w3.org/2000/svg` or just `svg` or what.  I think that would be the first thing to clarify.

**Comment by tbe** [comment]
From Slack discussion:
- the HTML parser sets `svg` or `math` as `Namespace` on elements that are part of these namespaces. Else the `Namespace` attribute is always empty

**Comment by bradleypeabody** [comment]
This is all done and merged now.
