### ISSUE TITLE
How do I create a small Vugu binary that can run in Kubernetes?

### ISSUE THREAD

**Issue by ilanpillemer** [vugu/vugu#135]
**Question**

How do I create a **_small_** Vugu binary that can run in Kubernetes?

**Is your question related to a problem? Please describe.**

I cannot use for example a _scratch_ image, but all I could find that works is to use the _golang:alpine_ image.

This means that my "micro" service when deployed is over 100M.

**Suggested Changes**

Provide an example _Dockerfile_ for running a Vugu app that requires the minimum size. And explain what the minimum size is, and the reasons. If it is 100M+, because that is _the way it is_ - then it would be useful to know.

**Additional context**
This is an example of a _Dockerfile_ that works but creates an image that is 100M+

```
FROM golang:alpine
RUN apk update && apk upgrade && apk add --no-cache bash git openssh
RUN go get -u github.com/vugu/vgrun && vgrun -install-tools
COPY server /app/
COPY cmd/server/ /app/
WORKDIR /app/
CMD ["/app/server"]
```

**Comment by ilanpillemer** [comment]
looks like I missed the distribution section in the docs... I will read through that and if that doesn't solve my questions, I will re-open.

**Comment by bradleypeabody** [comment]
Be aware that the golang Docker images contain the Go compiler.  You do not need it in order to run an executable that has been built with Go.  Something like this might be of help: https://dzone.com/articles/how-to-create-the-smallest-docker-image-for-your-g

Also, the base images are cached by Docker.  So if you're concerned about deployment speed, using a larger base image is not normally a problem.  What problem are you trying to solve by reducing size?

**Comment by ilanpillemer** [comment]
I was using the development server that does seem to need the Go binary. That was my mistake.
Having a 7mb image vs 120mb makes a difference when running microservices in Kubernetes. Yes, I normally use scratch or alpine. And its more the kubernetes than the docker that I need the small size as in the end you pay for everything when running on cloud services. (I run on Digital Ocean)
