### ISSUE TITLE
D3.js and Vugu?

### ISSUE THREAD

**Issue by ilanpillemer** [vugu/vugu#136]
**Question**
I want to use D3.js, will that be possible if I am using Vugu?

**Is your question related to a problem? Please describe.**
I noticed an issue saying you cannot have other js in the top level Vugu file? Does that mean I can't use D3.js in tandem with Vugu?

**Suggested Changes**
I am unsure if you can or cant use D3.js. But being able to use D3 is a critical for my hobby project I am about to start. I guess I could put the graphs on different app. But don't think I will want to do that.

**Comment by bradleypeabody** [comment]
I don't think anyone has tried this yet.  The first thing you'll likely run into is that I believe JS `<script>` tags only work with the static renderer, not with the regular DOM renderer.  (This is not terribly difficult to fix though, I could probably have something for this within the next few days if it's important.)

Meanwhile if you look at the contents of devserver.go from the "simple" example (https://github.com/vugu-examples/simple/blob/master/devserver.go) you'll see that it's using a simple string replace to put in a stylesheet - you should be able to do the same thing with `<script>` tags.  From there you should be able to use [vg-js-populate](https://www.vugu.org/doc/files/markup#vg-js-populate) to get a reference to a DOM element in your Vugu code and then call out to tell D3 what to do with it.  Or you could just reference it by the `id` attribute.  Be aware that changes in the Vugu DOM structure (e.g. showing or hiding an element) can cause the underlying elements on the page to be re-created and you might need to re-initialize your D3 chart in this case.  Probably don't worry about it to start but if you get issues where the chart is being vaporized after a Vugu event, this is probably why and what to do to fix.

I'd be really interested to hear how this turns out of you try it.

**Comment by ilanpillemer** [comment]
Great! Based on your reply I will definitely go forward then and try it. I started my hobby project last night, and will be working on it every evening. 

Should I keep this issue open to post updates as I proceed?

**Comment by bradleypeabody** [comment]
Excellent!  Yeah that's fine, go ahead and put any updates or questions here.
