### ISSUE TITLE
K/V Store

### ISSUE THREAD

**Issue by charles-d-burton** [vugu/vugu#138]
**Question**
Is there a mechanism for browser persistence? Meaning something like a K/V store that persists similar to Vuex or Redux?

**Is your question related to a problem? Please describe.**
No, mostly just curious.

**Additional context**
Mostly interested in this for login persistence.  So that once I establish a session with a backend I can resume it.

**Comment by bradleypeabody** [comment]
There are a few different aspects to this.

To preserve a token from the backend I would suggest [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage), which you can access via something like `js.Global().Get("localStorage").Call("setItem", "somekey", "somevalue")`.

For Vuex, which is shared state throughout the application, I think this will work quite differently in Vugu than it does in Vue, due to the nature of how Go deals with data vs Javascript.  The general idea is to just use structs and pointers and not have "data binding" per-se.  But it does need more experimentation to find and document good patterns.

**Comment by charles-d-burton** [comment]
Is that callable from within a go function or do I have to get it in the HTML?  Kind of noob question but I'm probably the most clueless frontend dev on the planet.

**Comment by bradleypeabody** [comment]
The code above is regular Go code that uses [syscall/js](https://golang.org/pkg/syscall/js/), you can call it from anywhere.

**Comment by charles-d-burton** [comment]
I ended up wirting a tiny little helper function and that did the trick perfectly, plus it's re-usable:

```go
package main

import "syscall/js"

func setLocal(key, value string) {
	js.Global().Get("localStorage").Call("setItem", key, value)
}

func getLocalString(key string) string {
	return js.Global().Get("localStorage").Call("getItem", key).String()
}```
