### ISSUE TITLE
Cookies?

### ISSUE THREAD

**Issue by Nv7-GitHub** [vugu/vugu#160]
**Question**
I couldn't find anything about cookies in the godoc. How do I use cookies in Vugu? Is there a Vugu method or should I just call javascript?

**Comment by bradleypeabody** [comment]
Vugu does not have anything specific to deal with cookies.  For now, call out to JS via the `js` package.  If you encounter something where it seems like it would be appropriate to wrap certain functionality in Vugu, go ahead and create an issue with that proposal. Although generally, from what I can see now, it seems out of scope for the Vugu project, since it would pretty much just be wrapping a few calls out to JS.

**Comment by Nv7-GitHub** [comment]
Ok, thank you!
