### ISSUE TITLE
Consider moving to `task` for builds

### ISSUE THREAD

**Issue by bradleypeabody** [vugu/vugu#225]
Recent changes to the Go tooling have made using `go run somescript.go` for build tooling increasingly difficult.   Between the module system which expects a go.mod to be present and match the imports even for such standalone tools, and the fact that dependencies require a `go get` before use (instead of being downloaded automatically) - these changes while they exist for good reason, basically broke what Vugu has been recommending for builds.  There are workarounds using the GO111MODULE option and others, but they are not particularly obvious or simple.

What we need is essentially very simple.  Something akin to a Makefile that runs the same on Windows/Linux/Mac and can be installed with a single command and then executed with another single command is all most projects typically need.

`task` (https://taskfile.dev) seems to be a good fit.  It is also written in Go.

We'll need some good examples and documentation of the recommended approach, but so far I think this would alleviate a good deal of the build pain that is developed around Vugu with recent Go releases.

And also just to be clear, while the commands we need to run are typically simple - vugugen with some arguments and then go build with some arguments, it's still more than we want developers to have to remember.  A consistent build by just typing `task` and then a consistent local development run with something like `task run` is what we're after.

**Comment by gedw99** [comment]
https://github.com/mdouchement/fichenn/blob/master/Taskfile.yml seems like a good example

**Comment by owenwaller** [comment]
For completeness there is also [Mage](https://magefile.org/)

But I want to suggest a different approach, especially for production.

I think we need to document what you need to do to build a vugu application using the standard go tools, so calling `go generate` or `go build` with the `GOOS=js` and `GOARCH=wasm` set.

If this is clearly documented then teams that need the information, like mine and we are using Makefiles, will know what to do.

I have no objection to supporting a 3rd party build system or providing Vugu tooling to help e.g. `vugugen` etc. if that helps get folks started, or if it is what the community asks for.

Also, what I don't want is to have a to have a full Go toolchain on any of my production servers. So things like this:

https://github.com/vugu/vugu/blob/885d6b14f1fe3b110fcf301e85e09025bd927009/simplehttp/simple-handler.go#L238-L241

In the `simplerhttp` package, which is the current recommended approach for distribution, I don't think will fly for us. 

We just need a way to produce the WASM artefact, and then we can serve it however we want. I've no objection to using a Go HTTP server for this, but this leaves open the possibility of nginx, or apache etc.

**Comment by powerman** [comment]
Personally I do not recommend Taskfile. It's about 7 years since they've released 1.0.0, but it still have really weird issues with environment variables priorities: these priorities are not documented (sic!), they work in really counter-intuitive and unique to task tool way, and even this unique way to handle env vars is not really intentional and have bugs. If you're interested in more details then check https://taskfile.dev/experiments/env-precedence/ (a month old attempt to fix these issue) and related issue https://github.com/go-task/task/issues/1038. With this situation in mind you can guess how many other similar issues Taskfile have.

As for Mage - I wonder how is your experience with it? Is it really better than shell scripts in your opinion? Any pros/cons of top of your mind?

**Comment by owenwaller** [comment]
@powerman 

This issue really should have been closed, as the `mage` based build was first merged in with PR #272.

As for a `mage` experience report it's great. It is much much easier than anything else we have tried. It's was trivial to convert the build process to Go and you gain all of the power of the Go tool chain - so your build script is now testable. `Mage` comes with quite a nice [shell helper module](https://pkg.go.dev/github.com/magefile/mage/sh) that helps simplify things. It's also as cross platform as Go is, which was important to `vugu` as we need the Windows support.

You just need to be careful that you don't shell out unless you need to to remain cross platform. So for example, we need to copy the `wasm_exec.js` file from the `GOROOT`. We can't do that via the shell with `cp ....` because that doesn't work with a Windows PowerShell or Command Prompt. So you need to write the a version of the `cp` command in Go yourself. See the [`modulehandler.go`](https://github.com/vugu/vugu/blob/master/magefiles/modulehandler.go#L233C6-L233C30) file for an example. 

Where we do shell out - to `docker` and `git` - we check that both are installed locally. We could in principle replace these with direct calls to the `docker` or `go-git` APIs which would remove the dependency on the external tools. We haven't done this yet and have no plans to do so ATM.

The `magefile` has been refactored several since PR #272. If you compare it to the latest version and you'll see they are quite different.

Perhaps our biggest improvement is that we can now run locally exactly the same process as the Github Action runs on a push. If you look at the [Github Action file](https://github.com/vugu/vugu/blob/master/.github/workflows/go-stable.yml) all that does is:

* install the latest stable version of Go
* install `mage`
* run `mage -v GithubAction` as a target. 

The rest of the built process is then handled by mage. So a `mage -v GithubAction` does the same thing if run locally.

My one tip for using `mage` would be to make the `magefiles` directory in your project a separate module. If you don't any imports that you only require for the build process will be added to your projects root `go.mod` file which isn't what you want. See:
[Issue #502](https://github.com/magefile/mage/issues/502) in the `mage` repo for the discussion of what I tried and how to fix it.

We do have a lot of targets in the `magefile` ATM (run `mage -l` to list them), but they are all used, as the `magefile` has grown organically. These may or may not get reduced/combined in some far off future PR. 

So yes, I think it's excellent. I'd recommend it. I've got a TODO  note to move all of my projects to a `mage` based build - which would replace a string of `Makefiles` in those cases.

Owen

**Comment by powerman** [comment]
Great, thanks!

At a glance I expect few UX issues with mage: missing shell completion for targets and missing optional args (flags) for targets. I've seen a several attempts to implement completion in mage issues but have no idea which one (if any) is actually works. As for optional args for target it looks like the workarounds are either put them into custom env var or provide them in required arg of string type and parse manually.

Also it's a bit scary mage wasn't maintained for about a year, but looks like author is planning to change this soon.

**Comment by powerman** [comment]
> that would I think be a shell issue not a `mage` issue, and may not be portable even on *nix

That's correct in theory. In practice this is usually solved by implementing 3-4 extra options/subcommands in the each tool: output completion script for bash, zsh, fish and sometimes even powershell. Some Go CLI libraries like Cobra provides such a feature out of box. So, it should be implemented in Mage tool for good UX.

Anyway, thanks for your responses, but I think we should stop - after all it's an offtopic for this repo.
