### ISSUE TITLE
"Getting Started" in 2024?

### ISSUE THREAD

**Issue by tjohnston-cd** [vugu/vugu#320]
The vugu.org website (getting started etc) is very outdated at the moment. It points toward the go 1.14-era tools, which internally call `go get` to install vgrun, set up the example project and so on. They're incompatible with newer go versions, so it makes me wonder what other parts of this might be.
I started down the road toward making these work in 1.23, then I noticed this repository is very active - lots of very promising work: 1.22 support, 1.23 support in progress, new buildsystem and so on. I checked out the godoc page and the contributors guide, which I think I understood (but there's a lot of detail there that isn't important to me right now as a new user).

After skimming through all that, I don't feel like I have a 3 minute "do this to get started with newer go versions" idea in mind. The godoc site actually points back at the vugu.org site while saying "You must have Go v1.22.3 as a minimum to use vugu". The example repos are still outdated and point at the 1.14-era stuff too - it looks like only `vugu/vugu` is updated and the others are unmaintained, it's not clear if that's deliberate or if the others are meant to be unused now..

I'm not trying to throw stones - Vugu looks great and I'm very interested in using it in my project, perhaps making some small contributions along the way and so on. Just confused about where to begin, between the old website and the new repo. 

# So.. I'm sorry if I missed something, but my question is this:
What do I do to get started using vugu with go 1.22 or 1.23 today? 
Do I need to read and understand all this stuff about mage and unit tests? What is the simplest path for me to take?

**Comment by owenwaller** [comment]
Hi @tjohnston-cd

Thanks for the feedback, it's really helpful to us. Sorry to hear you are having difficulties, @bradleypeabody and myself do hear you. 

This is also one outstanding PR ATM - PR #319 which puts back the 'Readme.md` in the rot of the repo. It was accidentally removed a few weeks ago and we only picked it up this week. I suspect if that had have been there it might have been helpful to you.

We are aware than the [vugu docs site](https://www.vugu.org/) site is beginning to _look_ progressively out of date, especially with references to the `go` version. I'd missed than this has also impacted the information on [Go docs website](https://pkg.go.dev/github.com/vugu/vugu).

ATM neither of us have had the time to update the documentation because a) `vugu` been a moving target and b) we don't want to impose a build system on _users_, but we do on _contributors_.  But it sounds like we might need to start fixing this as a priority then.

### Quick ways to build a `vugu` project

If you just want to start using vugu for a project then the reference __I__ would suggest is the one in the [wiki](https://github.com/vugu/vugu/wiki/Building-With-Go-and-Deploying-with-nginx). This guide will tell you how to build an simple `vugu` application using only the standard Go toolchain. So no `mage` or `vgrun` required. To serve the new application you'll still need a web server. The Guide uses the default `nginx` container from the `nginx` team rather than the `devserver.go`. These where the steps that formed the basis of the first version of the `magefile`that is used to build and test `vugu` itself.

This is the simplest path for you to take, and will work with the last two supported versions of Go go1.22.X and go1.23.X.


You can then wrap these instructions in whatever build tool you prefer to use if you don't want to go though multiple shell commands each time to build your project.

These instructions should be correct :crossed_fingers: but they where written a year ago and I haven't tried them since.
If they don't work for you can you please let us know? We'll correct the instructions as necessary.

But, AFAIK, the `vgrun` approach listed on [vugu docs site](https://www.vugu.org/) site will actually still work. I do not believe anything has been done within the `vugu` project that stops these instructions working.. But as I don't build `vugu` or any `vugu` applications using these instructions I'm not in the best place to offer advice.

### Building the examples

The examples in the `vugu` repo can be built with and without using `mage`. The [Readme](https://github.com/vugu/vugu/blob/master/examples/Readme.md) in the `examples` package has the details.

The intent of these examples is to show users how to use specific features of `vugu` such as the `vg-for` loop construct. In particular the package much not depends on an external tools or any servers/services that need to be installed locally e.g. a database for a shop example. However an well known internet based service can be used, as used by the `fetch-and-display` example.

_Note: I cam currently in the process of creating a number of new examples, so this package is currently subject to some change at the minute as new examples are added. I can't guarantee that there won't be breaking changes made to the existing examples ATM._

The status of the [`vugu-examples`](https://github.com/vugu-examples) repo is uncertain at the minute. I am not sure ehich examples apart form the `simple` example builds ATM. 

My _personal_ view is the `vugu-examples` repo will become a collection of examples that require external tools e.g. CSS generators or web servers fronting databases. So a collection of complete applications both front and backend. This is a subject of ongoing debate between @bradleypeabody and myself.

### Building if you want to contribute to the `vugu` project

Contributions to `vugu` both large and small are very welcome indeed.

If you want to contribute you will need to follow the [Contributors guide](https://github.com/vugu/vugu/blob/master/CONTRIBUTING.md).

When contributing you'll need to use the `mage` build tool to build and test your change. We use `mage` as the build tool for the project because we need:

1. A cross platform build tool - `vugu` should build wherever Go builds. We can't achieve this via Makefiles, bash scripts, or YAML approaches like `Taskfile`. We have tried all of those and none of them worked everywhere, particularly on Windows.
2. We need consistency with the Github Action CI?CD pipeline (hint: you can run the Github action locally with `mage -v GithubAction`)
3. We need to be a dependency free as possible. So apart from Go and `mage` the only other dependencies the build system needs are:

**Comment by owenwaller** [comment]
@tjohnston-cd sorry I accidentally hit "Send" while I was editing the reply to you. It's now complete. Hopefully it'll be enough to get you started with `vugu`.

Owen

**Comment by owenwaller** [comment]
@tjohnston-cd and I have just merged PR #319 for you, so the full Readme is back in the repo.

**Comment by tjohnston-cd** [comment]
Thanks very much - that's lots of great info. 
My goal right now is to get the equivalent of the quickstart guide from the main website, but with newer `go` / newer `vugu`. So.. I'm looking to set up the minimal set of files/changes to build the static assets (`go.dist` example from the site) and then serve them.

At first glance, it looks like the wiki page has exactly what I'm after (although I should say my reaction was "there's stuff on the wiki too?!")

Will dig in as soon as I can and let you know how it goes. Thanks again.

**Comment by owenwaller** [comment]
@tjohnston-cd 

NP. The wiki instructions are an exact replica of the "Getting Started" (the so called `simple`) example on the `vugu.org` website. So pretty much everything you need is already there.

As for the [`dist.go`](https://www.vugu.org/doc/build-and-dist) I'd forgotten we even had this, but I'd now say it is not such a good idea to follow it exactly. 

The `dist.go` depends on the `distutil` package, which is under threat of removal at this point. It's only used by itself (in the tests) and the `legacy-wasm-test-suite`. The later is going to be deleted RSN, which will remove the need for the `distutil` package as well (and other packages). If we remove packages from the `vugu` repo then, in general, we have less to maintain going forward. 

It also appears that `go.dist` references the `simplethttp` package which is under similar threat of removal, and a template file that doesn't exist in the `// STATIC FILE` comment in the code.

The `legacy-test-suite` has been completely (*) replaced by the `wasm-test-suite` which is both much easier to follow and much faster to execute.

If you want an equivalent of the `dist.go` then I'd use a separate build tool to do a similar job. Whether that build tool used `Go` or not is immaterial, provided it does what you need, on the systems you work on and deploy to. We can't know this which is why we leave this up to the users of `vugu`.

And remember the `dist.go` program doesn't copy anything to the server, so you still need that stage.

There __might__ be at some point in the future be a new `vugu` tool (name to be decided) that will act as a bootstrap for you to give you a minimal `index.html` and `root.vugu` and `root.go` file in a similar way to `vgrun -new-from-example=simple .` command does today - but based on Go templates for the html and not a external Github repo. This would save you having a copy files and call `go mod init` etc. as is currently the case in the `wiki` instructions. But as I said that is in the future....

Hopefully that helps.

Owen

(*) There are two tests in the `wasm-test-suite` that are skipped, but the equivalent tests pass in the `legacy-wasm-test-suite` Once these tests are fixed the `legacy-wasm-test-suite` will be removed. See issues #278, #279, #280, #282, #321, #322

**Comment by tjohnston-cd** [comment]
Thanks - I followed all the wiki page instructions and everything worked. I just needed to install `vugugen` myself as it mentions near the top.

Regarding the `dist.go` stuff, I can definitely just build my own setup that repeats part of what the wiki page describes and packages it in a container image as the nginx example shows. 

I'm 99% sure I have everything I need to go from here. I'll try to put the rest of my project together and check in here for updates. Closing this for now - feel free to reopen if you like.
