### ISSUE TITLE
Some problems about Refactor

### ISSUE THREAD

**Issue by itstmyi** [vugu/vugu#78]
https://github.com/vugu/vugu/wiki/Refactor-Notes---Sep-2019

Q1:
JS Property Assignment Syntax
Example:
<input type="checkbox" .checked="false"/>

Should  "/" before ">"  be deleted ? 
I means no closed label "/" is needed for "input" html element .
 Errors still appear after I run "go run" and access it by browser ,even if I delete the above "/" .

Q2:
New and Improved DOM Event Handling
Example:
<input type="text" @ changed="c.HandleChanged(event)">

This is really cool for having resolved my prior question partly at #65 .
In my opinion , Vugu Event "@ click" stands for JS Event "onclick" , so  JS Event "onchange" should be written as "@ change" in Vugu file. Your sample code defined unknown JS Event "onchanged" and "event.PropString" returned nothing.

New updated documents are expected eagerly .
Thanks .  Good job !

**Comment by JalonSolov** [comment]
The / before the > makes it proper XHTML code, as opposed to HTML.  It is the same thing with list elements, where it is common to see

<li>first
<li>second
<li>third

Where XHTML requires the closing tag

<li>first</li>
<li>second</li>
<li>third</li>

The difference is that HTML is very lenient about things like closing tags, closing tags out of order, etc.  XHTML is very strict about those things.

XHTML is worth it if you don't want to have to track down obscure problems that only happen on certain versions of certain browsers... just because you skipped a closing tag, or put them out of order like

<b><u>text</b></u>

which _should_ be

<b><u>text</u></b>

(you are supposed to close tags in opposite order of opening)

**Comment by itstmyi** [comment]
Thanks .
