### ISSUE TITLE
html tag attributes are not sync

### ISSUE THREAD

**Issue by tbruyelle** [vugu/vugu#81]
**Describe the bug**
If I add attributes to my `<html>` tag inside a `root.vugu`, there are absent from the rendered version. I didn't test with other tags like `<body>` but it's maybe impacted too.

**Software Versions**
Vugu version: c4c2de3e9ddf5cfa914d42e7205ade62b4369e74
Go version: 1.13.4
Browser and version: Chromium 78.0.3904.108 (Official Build) Arch Linux (64-bit)

**To Reproduce**
root.vugu that starts with `<html class="whatever">`

**Expected behavior**
The attributes from html tag should be copied from the root.vugu to the rendered version.

**Comment by bradleypeabody** [comment]
Thanks for reporting this. This one requires a bit more since the treatment of the html, head and body tags each require some special treatment, as well as all of the contents of the head tag.  I'll see if this can be fixed soon though - it's definitely a needed feature to make "full HTML support" usable in real-world applications.

**Comment by tbruyelle** [comment]
@bradleypeabody I coded something to sync the html attributes, it probably requires fixes and refinement, can I open a MR to present you that ?

**Comment by bradleypeabody** [comment]
@tbruyelle Great!  Yes please do.

**Comment by tbruyelle** [comment]
@bradleypeabody Cool, the PR is there :)
